//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUNGSANPHAM
    {
        public int MASP { get; set; }
        public int MAKICHCO { get; set; }
        public int SOLUONG { get; set; }
    
        public virtual KICHCO KICHCO { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
