//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class CUSTOMER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUSTOMER()
        {
            this.DONHANGs = new HashSet<DONHANG>();
            this.RATINGs = new HashSet<RATING>();
        }
    
        public int MACUSTOMER { get; set; }
        [Display(Name="Họ tên")]
        public string TENCUSTOMER { get; set; }
        public Nullable<System.DateTime> NGAYDK { get; set; }
        [Display(Name = "Ngày sinh")]
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        [Display(Name = "Số điện thoại")]
        public string SDT { get; set; }
        [Display(Name = "Email")]
        public string EMAIL { get; set; }
        [Display(Name = "Mật khẩu")]
        public string MATKHAU { get; set; }
        public Nullable<int> RATING { get; set; }
        public Nullable<int> TINHTRANG { get; set; }
        [Display(Name = "Địa chỉ")]
        public string DIACHI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DONHANG> DONHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RATING> RATINGs { get; set; }
    }
}
