//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONHANG
    {
        public int MADH { get; set; }
        public int MACUSTOMER { get; set; }
        public Nullable<System.DateTime> NGAYMUA { get; set; }
        public Nullable<double> TONGTIEN { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
    }
}
