//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class KICHCO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KICHCO()
        {
            this.CTDHs = new HashSet<CTDH>();
            this.CUNGSANPHAMs = new HashSet<CUNGSANPHAM>();
        }
    
        public int MAKICHCO { get; set; }
        public int MADOITUONG { get; set; }
        public int KICHCO1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDH> CTDHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUNGSANPHAM> CUNGSANPHAMs { get; set; }
        public virtual DOITUONG DOITUONG { get; set; }
    }
}
