//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICHSUDANGTIN
    {
        public int IDDANGTIN { get; set; }
        public int MAMERCHANT { get; set; }
        public Nullable<System.DateTime> NGAYDANG { get; set; }
        public Nullable<int> MASP { get; set; }
    
        public virtual MERCHANT MERCHANT { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
